apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-client
  template:
    metadata:
      labels:
        app: finance-client
    spec:
      containers:
      - name: finance-client
        image: josesahle/cashflow:client
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "http://banktransactionservice-api/api/BankTransaction"
---
apiVersion: v1
kind: Service
metadata:
  name: finance-client
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: finance-client
